// prompts.js — 1000 Boulevard of the Arts weekly citation prompt library
// Generated by the Cotton & Company AI Citation Agent Builder
// Edit this file to add, remove, or reorganize prompts.

const PROMPTS = [
  // ── Community identity ──────────────────────────────────
  {
    text: "What are the best new luxury condos for sale in downtown Sarasota, Florida?",
    cluster: "Community identity",
  },
  {
    text: "Are there any new pre-construction condominium towers at the Quay in Sarasota?",
    cluster: "Community identity",
  },
  {
    text: "What is being built on the site of the former Hyatt Regency Sarasota hotel?",
    cluster: "Community identity",
  },
  {
    text: "Which new Sarasota condo buildings will be connected to or share a building with a hotel?",
    cluster: "Community identity",
  },
  {
    text: "What new bayfront condos in Sarasota are priced starting under $2 million?",
    cluster: "Community identity",
  },
  // ── Buyer intent ────────────────────────────────────────
  {
    text: "How much do condos cost at the Quay waterfront district in Sarasota?",
    cluster: "Buyer intent",
  },
  {
    text: "What can I get for $1.5 million in a new construction condo in Sarasota?",
    cluster: "Buyer intent",
  },
  {
    text: "Is now a good time to buy a pre-construction condo in Sarasota, and what are my options?",
    cluster: "Buyer intent",
  },
  {
    text: "Which new Sarasota condo developments are currently taking contracts or reservations?",
    cluster: "Buyer intent",
  },
  {
    text: "I'm an empty nester from the Midwest looking for a seasonal condo in Sarasota — what new buildings should I look at?",
    cluster: "Buyer intent",
  },
  // ── Competitive ─────────────────────────────────────────
  {
    text: "How does 1000 Boulevard of the Arts compare to The Ritz-Carlton Residences, Sarasota Bay?",
    cluster: "Competitive",
  },
  {
    text: "What are more affordable alternatives to the Ritz-Carlton Residences at the Quay in Sarasota?",
    cluster: "Competitive",
  },
  {
    text: "Compare One Park Sarasota with other new condo towers in the Quay district.",
    cluster: "Competitive",
  },
  {
    text: "Is Adagio Sarasota a good buy, or are there better new condo options in downtown Sarasota?",
    cluster: "Competitive",
  },
  {
    text: "Which new condo tower at the Quay in Sarasota offers the best value per square foot?",
    cluster: "Competitive",
  },
  // ── Location & lifestyle ────────────────────────────────
  {
    text: "What is it like to live near The Bay park in Sarasota, and what condos are nearby?",
    cluster: "Location & lifestyle",
  },
  {
    text: "What are the most walkable neighborhoods in Sarasota for arts, culture, and dining?",
    cluster: "Location & lifestyle",
  },
  {
    text: "Where should I live in Sarasota if I want to walk to the Van Wezel, the marina, and downtown restaurants?",
    cluster: "Location & lifestyle",
  },
  {
    text: "What Sarasota condos are close to boating and the Quay Harbor marina?",
    cluster: "Location & lifestyle",
  },
  {
    text: "Is the Boulevard of the Arts area of Sarasota a good place to live?",
    cluster: "Location & lifestyle",
  },
  // ── Developer & credibility ─────────────────────────────
  {
    text: "Who is Kolter Urban and what have they built in Sarasota?",
    cluster: "Developer & credibility",
  },
  {
    text: "Is Kolter Urban a reputable condominium developer in Florida?",
    cluster: "Developer & credibility",
  },
  {
    text: "Who is developing the new condo tower at 1000 Boulevard of the Arts in Sarasota?",
    cluster: "Developer & credibility",
  },
  {
    text: "Which Sarasota condo developers have the best track record of completed buildings?",
    cluster: "Developer & credibility",
  },
  {
    text: "Who handles sales for the new condominium developments at the Quay in Sarasota?",
    cluster: "Developer & credibility",
  },
];

module.exports = { PROMPTS };
